#!/usr/bin/env python3
"""
MediaCore Setup Wizard
Interactive setup script for configuring and initializing MediaCore.
"""

import os
import sys
import subprocess
import platform
import shutil
import urllib.request
import gzip
from pathlib import Path

# Colors for terminal output
class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    END = '\033[0m'
    BOLD = '\033[1m'

def print_header(text):
    print(f"\n{Colors.HEADER}{Colors.BOLD}{'='*60}{Colors.END}")
    print(f"{Colors.HEADER}{Colors.BOLD}  {text}{Colors.END}")
    print(f"{Colors.HEADER}{Colors.BOLD}{'='*60}{Colors.END}\n")

def print_step(text):
    print(f"{Colors.CYAN}>> {text}{Colors.END}")

def print_success(text):
    print(f"{Colors.GREEN}[OK] {text}{Colors.END}")

def print_warning(text):
    print(f"{Colors.YELLOW}[!] {text}{Colors.END}")

def print_error(text):
    print(f"{Colors.RED}[ERROR] {text}{Colors.END}")

def ask_yes_no(question, default=True):
    """Ask a yes/no question."""
    default_str = "Y/n" if default else "y/N"
    while True:
        answer = input(f"{Colors.BOLD}{question} [{default_str}]: {Colors.END}").strip().lower()
        if answer == "":
            return default
        if answer in ["y", "yes", "j", "ja"]:
            return True
        if answer in ["n", "no", "nein"]:
            return False
        print("Please answer yes or no.")

def ask_input(question, default=""):
    """Ask for user input with optional default."""
    default_str = f" [{default}]" if default else ""
    answer = input(f"{Colors.BOLD}{question}{default_str}: {Colors.END}").strip()
    return answer if answer else default

def run_command(cmd, cwd=None, check=True):
    """Run a shell command."""
    try:
        result = subprocess.run(
            cmd,
            shell=True,
            cwd=cwd,
            check=check,
            capture_output=True,
            text=True
        )
        return result.returncode == 0, result.stdout, result.stderr
    except subprocess.CalledProcessError as e:
        return False, e.stdout, e.stderr

def check_python():
    """Check Python version."""
    version = sys.version_info
    if version.major < 3 or (version.major == 3 and version.minor < 10):
        print_error(f"Python 3.10+ required. Found: {version.major}.{version.minor}")
        return False
    print_success(f"Python {version.major}.{version.minor}.{version.micro}")
    return True

def check_node():
    """Check Node.js installation."""
    success, stdout, _ = run_command("node --version", check=False)
    if success and stdout:
        version = stdout.strip()
        print_success(f"Node.js {version}")
        return True
    print_error("Node.js not found. Please install Node.js 18+")
    return False

def check_npm():
    """Check npm installation."""
    success, stdout, _ = run_command("npm --version", check=False)
    if success and stdout:
        version = stdout.strip()
        print_success(f"npm {version}")
        return True
    print_error("npm not found")
    return False

def setup_env_file(project_root):
    """Create or update .env file."""
    env_file = project_root / ".env"

    # Check if .env already exists
    existing_config = {}
    if env_file.exists():
        print_warning(".env file already exists")
        if not ask_yes_no("Do you want to reconfigure?", default=False):
            return True
        # Read existing values
        with open(env_file, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    existing_config[key.strip()] = value.strip()

    print_step("Configuring environment variables...")

    # Get TMDB API Key
    default_key = existing_config.get("TMDB_API_KEY", "")
    tmdb_key = ask_input("Enter your TMDB API Key", default_key)

    if not tmdb_key:
        print_warning("No TMDB API Key provided. You can add it later to .env")
        print_warning("Get your API key at: https://www.themoviedb.org/settings/api")

    # Write .env file
    env_content = f"""# MediaCore Configuration
# Generated by setup.py

# Required: TMDB API Key (for live data fetching)
TMDB_API_KEY={tmdb_key}

# Optional: Server settings
HOST=0.0.0.0
PORT=8000
DEBUG=false

# Optional: List auto-update interval (hours)
UPDATE_INTERVAL=6
"""

    with open(env_file, "w") as f:
        f.write(env_content)

    print_success(f"Configuration saved to {env_file}")
    return True

def setup_backend(project_root):
    """Setup backend virtual environment and dependencies."""
    backend_dir = project_root / "backend"
    venv_dir = backend_dir / "venv"

    print_step("Setting up backend...")

    # Check if venv exists
    if venv_dir.exists():
        print_warning("Virtual environment already exists")
        if not ask_yes_no("Reinstall dependencies?", default=False):
            return True
    else:
        # Create virtual environment
        print_step("Creating virtual environment...")
        success, _, stderr = run_command(f'"{sys.executable}" -m venv venv', cwd=backend_dir)
        if not success:
            print_error(f"Failed to create venv: {stderr}")
            return False
        print_success("Virtual environment created")

    # Determine pip path
    if platform.system() == "Windows":
        pip_path = venv_dir / "Scripts" / "pip.exe"
    else:
        pip_path = venv_dir / "bin" / "pip"

    # Install dependencies
    print_step("Installing backend dependencies...")
    success, _, stderr = run_command(f'"{pip_path}" install -r requirements.txt', cwd=backend_dir)
    if not success:
        print_error(f"Failed to install dependencies: {stderr}")
        return False

    print_success("Backend dependencies installed")

    # Create data directory
    data_dir = backend_dir / "data"
    data_dir.mkdir(exist_ok=True)

    return True

def setup_api_central(project_root):
    """Setup api-central dependencies."""
    api_central_dir = project_root / "api-central"

    print_step("Setting up API Central (IMDb data)...")

    # Use the same venv as backend
    backend_venv = project_root / "backend" / "venv"

    if platform.system() == "Windows":
        pip_path = backend_venv / "Scripts" / "pip.exe"
    else:
        pip_path = backend_venv / "bin" / "pip"

    # Check for requirements.txt in api-central
    req_file = api_central_dir / "requirements.txt"
    if req_file.exists():
        print_step("Installing API Central dependencies...")
        success, _, stderr = run_command(f'"{pip_path}" install -r requirements.txt', cwd=api_central_dir)
        if not success:
            print_warning(f"Some dependencies may have failed: {stderr}")

    print_success("API Central configured")
    return True

def setup_frontend(project_root):
    """Setup frontend dependencies."""
    frontend_dir = project_root / "frontend"

    print_step("Setting up frontend...")

    # Check if node_modules exists
    node_modules = frontend_dir / "node_modules"
    if node_modules.exists():
        print_warning("node_modules already exists")
        if not ask_yes_no("Reinstall dependencies?", default=False):
            return True

    # Install npm dependencies
    print_step("Installing frontend dependencies (this may take a minute)...")
    success, _, stderr = run_command("npm install", cwd=frontend_dir)
    if not success:
        print_error(f"Failed to install npm packages: {stderr}")
        return False

    print_success("Frontend dependencies installed")
    return True

def build_frontend(project_root):
    """Build frontend for production."""
    frontend_dir = project_root / "frontend"
    backend_static = project_root / "backend" / "static"

    print_step("Building frontend for production...")

    success, _, stderr = run_command("npm run build", cwd=frontend_dir)
    if not success:
        print_error(f"Failed to build frontend: {stderr}")
        return False

    # Copy to backend/static
    dist_dir = frontend_dir / "dist"
    if dist_dir.exists():
        if backend_static.exists():
            shutil.rmtree(backend_static)
        shutil.copytree(dist_dir, backend_static)
        print_success(f"Frontend built and deployed to {backend_static}")

    return True

def import_imdb_data(project_root):
    """Download and import IMDb datasets."""
    api_central_dir = project_root / "api-central"
    backend_venv = project_root / "backend" / "venv"

    if platform.system() == "Windows":
        python_path = backend_venv / "Scripts" / "python.exe"
    else:
        python_path = backend_venv / "bin" / "python"

    cmd = f'"{python_path}" imdb_importer.py'

    print_step("Downloading and importing IMDb data...")
    print_warning("This will download ~500MB and may take several minutes.")
    print_warning("Press Ctrl+C to cancel.")

    try:
        subprocess.run(cmd, shell=True, cwd=api_central_dir)
        print_success("IMDb data import completed")
        return True
    except KeyboardInterrupt:
        print_warning("Import cancelled by user")
        return True
    except Exception as e:
        print_error(f"Import failed: {e}")
        return False

def start_application(project_root):
    """Start the backend server."""
    backend_dir = project_root / "backend"
    backend_venv = project_root / "backend" / "venv"

    if platform.system() == "Windows":
        python_path = backend_venv / "Scripts" / "python.exe"
    else:
        python_path = backend_venv / "bin" / "python"

    print_header("Starting MediaCore")
    print(f"{Colors.GREEN}Server starting at: http://localhost:8000{Colors.END}")
    print(f"{Colors.YELLOW}Press Ctrl+C to stop{Colors.END}\n")

    try:
        subprocess.run(f'"{python_path}" main.py', shell=True, cwd=backend_dir)
    except KeyboardInterrupt:
        print("\nServer stopped.")

def main():
    print_header("MediaCore Setup Wizard")

    # Get project root
    project_root = Path(__file__).parent.absolute()
    print(f"Project directory: {project_root}\n")

    # Check prerequisites
    print_step("Checking prerequisites...")
    if not check_python():
        sys.exit(1)

    node_ok = check_node()
    npm_ok = check_npm()

    if not (node_ok and npm_ok):
        print_error("Please install Node.js 18+ and try again")
        print("Download from: https://nodejs.org/")
        sys.exit(1)

    print()

    # Configuration
    print_header("Configuration")
    setup_env_file(project_root)

    # Backend setup
    print_header("Backend Setup")
    if not setup_backend(project_root):
        print_error("Backend setup failed")
        sys.exit(1)

    # API Central setup
    setup_api_central(project_root)

    # Frontend setup
    print_header("Frontend Setup")
    if not setup_frontend(project_root):
        print_error("Frontend setup failed")
        sys.exit(1)

    # Build frontend
    if ask_yes_no("Build frontend for production?", default=True):
        build_frontend(project_root)

    # Data import
    print_header("IMDb Data Import")
    print(f"""
{Colors.CYAN}IMDb data enables filtering by IMDb ratings.{Colors.END}
- Downloads ~500MB of data from IMDb
- Enables IMDb Rating and IMDb Votes filters
- Only needed for movies (TMDB data is fetched live)
""")

    if ask_yes_no("Download and import IMDb data?", default=True):
        import_imdb_data(project_root)

    # Done
    print_header("Setup Complete!")

    print(f"""
{Colors.GREEN}MediaCore has been set up successfully!{Colors.END}

{Colors.BOLD}To start the application:{Colors.END}

  Option 1 - Production mode (frontend served by backend):
    cd backend
    {'.\\\\venv\\\\Scripts\\\\activate' if platform.system() == 'Windows' else 'source venv/bin/activate'}
    python main.py

    Then open: http://localhost:8000

  Option 2 - Development mode (with hot reload):
    Terminal 1 (Backend):
      cd backend
      {'.\\\\venv\\\\Scripts\\\\activate' if platform.system() == 'Windows' else 'source venv/bin/activate'}
      python main.py

    Terminal 2 (Frontend):
      cd frontend
      npm run dev

    Then open: http://localhost:5173

{Colors.BOLD}Configuration:{Colors.END}
  Edit .env file to change settings (TMDB API key, etc.)

{Colors.BOLD}Data Sources:{Colors.END}
  - TMDB: Fetched live from API (requires TMDB_API_KEY)
  - IMDb: Local database (run: cd api-central && python imdb_importer.py)
""")

    # Offer to start now
    if ask_yes_no("Start MediaCore now?", default=True):
        start_application(project_root)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(0)
